name: Windows Packaging (Reusable)

on:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string
      channel:
        required: true
        type: string
      runtimePrefix:
        required: true
        type: string

env:
  GIT_CONFIG_PARAMETERS: "'core.autocrlf=false'"
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  __SuppressAnsiEscapeSequences: 1
  nugetMultiFeedWarnLevel: none
  SYSTEM_ARTIFACTSDIRECTORY: ${{ github.workspace }}/artifacts
  BUILD_ARTIFACTSTAGINGDIRECTORY: ${{ github.workspace }}/artifacts

jobs:
  package:
    name: Windows Packaging - ${{ inputs.architecture }} - ${{ inputs.channel }}
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1000

      - name: Capture Environment
        if: success() || failure()
        run: |
          Get-ChildItem -Path env: | Out-String -width 9999 -Stream | write-Verbose -Verbose
        shell: pwsh

      - name: Capture PowerShell Version Table
        if: success() || failure()
        run: |
          $PSVersionTable
        shell: pwsh

      - name: Switch to Public Feeds
        if: success()
        run: |
          Import-Module .\tools\ci.psm1
          Switch-PSNugetConfig -Source Public
        shell: pwsh

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: Bootstrap
        if: success()
        run: |
          Import-Module .\tools\ci.psm1
          Invoke-CIInstall -SkipUser
        shell: pwsh

      - name: Build and Package
        run: |
          Import-Module .\tools\ci.psm1
          New-CodeCoverageAndTestPackage
          Invoke-CIFinish -Runtime ${{ inputs.runtimePrefix }}-${{ inputs.architecture }} -channel ${{ inputs.channel }}
        shell: pwsh

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-packaging-${{ inputs.architecture }}-${{ inputs.channel }}
          path: |
            ${{ github.workspace }}/artifacts/**/*
            !${{ github.workspace }}/artifacts/**/*.pdb
